WaduCaseSolution/Areas/Admin/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using WaduCase.Common;
using WaduCaseBusiness.DAO;
using WaduCaseBusiness.Model;

namespace WaduCase.Areas.Admin.Controllers
{
    [SessionAuthorize]
    public class OrderController : Controller
    {

        public ActionResult Index(int status = 1)
        {
            var orders = OrderDAO.GetListOrderByStatusID(status);
            ViewBag.ListStatusOrder = OrderDAO.StaticOrderStatus();
            ViewBag.Status = status;
            if (orders == null)
            {
                orders = new List<OrderBO>();
            }

            return View(orders);

        }

        public JsonResult ViewOrder(string id)
        {
            var orders = OrderDAO.GetOrderByID(id);
            string html = String.Empty;
            if (orders != null && !String.IsNullOrEmpty(orders.id))
            {
                html = RenderRazorViewToString("_PartialDetailOrder", orders);
            }

            return Json(new
            {
                content = html
            }, JsonRequestBehavior.AllowGet);
        }
        public string RenderRazorViewToString(string viewName, object model)
        {
            ViewData.Model = model;
            using (var sw = new StringWriter())
            {
                var viewResult = ViewEngines.Engines.FindPartialView(ControllerContext,
                                                                         viewName);
                var viewContext = new ViewContext(ControllerContext, viewResult.View,
                                             ViewData, TempData, sw);
                viewResult.View.Render(viewContext, sw);
                viewResult.ViewEngine.ReleaseView(ControllerContext, viewResult.View);
                return sw.GetStringBuilder().ToString();
            }
        }
        [HttpPost]
        public ActionResult UpdateOrderStatus(FormCollection form)
        {
            UserLogin user = (UserLogin)Session[CommonConstants.USER_SESSION];
            string OrderID = Convert.ToString(form["orderid"]).Trim();
            int StatusID = Convert.ToInt32(form["selectstatus"]);


            var updateOrder = OrderDAO.GetOrderByID(OrderID);
            var result = -1;
            if (updateOrder != null && !String.IsNullOrEmpty(updateOrder.id) && updateOrder.id == OrderID)
            {
                updateOrder.status = StatusID;
                if (StatusID == 1)
                {
                    updateOrder.statusname = "Chưa xử lý";

                }
                else if (StatusID == 2)
                {
                    updateOrder.statusname = "Đang xử lý";

                }
                else if (StatusID == 3)
                {
                    updateOrder.statusname = "Đã hoàn tất";
                    updateOrder.deliverydate = DateTime.Now;

                }
                else if (StatusID == 4)
                {
                    updateOrder.statusname = "Đã hủy";
                    updateOrder.canceleddate = DateTime.Now;
                    updateOrder.iscanceled = true;
                    updateOrder.canceleduser = Convert.ToString(user.UserID);

                }
                result = OrderDAO.UpdateOrderStatus(OrderID, updateOrder);
            }


            return RedirectToAction("Index", new
            {
                status = result
            });
        }


        [HttpPost]
        public JsonResult DeleteOrder(string id)
        {
            UserLogin user = (UserLogin)Session[CommonConstants.USER_SESSION];
            string messageDelete = "";
            bool resultDelete = false;

            resultDelete = OrderDAO.DeleteOrder(id, user.UserID.ToString());
            messageDelete = "Xóa thành công";
            return Json(
                    new
                    {
                        status = resultDelete,
                        message = messageDelete
                    });
        }
    }
}

WaduCaseSolution/Controllers/ProductController.cs
using WaduCaseBusiness.DAO;
using WaduCaseBusiness.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WaduCase.Models;
using Newtonsoft.Json;

namespace WaduCase.Controllers
{
    public class ProductController : Controller
    {

        public ActionResult Index(string metatitle, int id, int attribute_pa_chon_chat_lieu_op_lung = 0, string cart_item_key = "")
        {

            if (metatitle.Length <= 0 || metatitle.Split('-').Count() <= 1)
            {
                return RedirectToAction("NotFound", "Error");
            }


            var product = ProductDAO.GetProductByID(id);
            if (product == null)
            {
                return RedirectToAction("NotFound", "Error");
            }
            product.avatar.OrderBy(x => x.displayorder);
            product.slide.OrderBy(x => x.displayorder);

            if (product.collectionid > 0)
            {
                ViewBag.CollectionName = BrandModel.GetCollectionByID(Convert.ToInt32(product.collectionid)).name;
            }
            else
            {
                ViewBag.BrandName = BrandModel.GetBrandByID(Convert.ToInt32(product.brandid)).name;
            }

            ViewBag.CurrentMaterialID = attribute_pa_chon_chat_lieu_op_lung;
            CartSession cart = new CartSession();

            if (!String.IsNullOrEmpty(cart_item_key))
            {
                List<CartSession> lstCartItem = Session["fancycart"] as List<CartSession>;
                if (lstCartItem != null)
                {
                    cart = lstCartItem.Where(x => x.ItemKey == cart_item_key).FirstOrDefault();
                }

            }
            if (cart == null) cart = new CartSession();
            if (!String.IsNullOrEmpty(cart.Order))
            {
                cart.OrderObject = JsonConvert.DeserializeObject<dynamic>(cart.Order);
                cart.OrderObject_Additional = cart.OrderObject.product[0];

            }

            ViewBag.CurrentCartItem = cart;
            var commonInfo = LocationDAO.GetCommonInfoByID("commoninfo");
            ViewBag.CommonInfo = commonInfo;
            return View(product);
        }

        public ActionResult RelativeProduct(ProductBO objProductBO)
        {
            var listRelativeProduct = ProductDAO.GetListRelativeProduct(objProductBO.id, Convert.ToInt32(objProductBO.brandid), Convert.ToInt32(objProductBO.collectionid));

            if (objProductBO.collectionid > 0)
            {
                ViewBag.CollectionName = BrandModel.GetCollectionByID(Convert.ToInt32(objProductBO.collectionid)).name;
                ViewBag.CollectionID = objProductBO.collectionid;
            }
            else
            {
                ViewBag.BrandName = BrandModel.GetBrandByID(Convert.ToInt32(objProductBO.brandid)).name;
                ViewBag.BrandID = objProductBO.brandid;
            }

            return PartialView(listRelativeProduct);
        }
        public ActionResult RealProductAtWaduCase(ProductBO objProduct)
        {
            int id = 3;

            List<RealCaseBO> lstRealCase = CollectionDAO.GetListRealCaseByCollectionID(id, 8);
            return PartialView(lstRealCase);
        }
    }
}

WaduCaseSolution/Areas/Admin/Views/Order/Index.cshtml
@using WaduCaseBusiness.Model
@model List<OrderBO>


@{
    ViewBag.Title = "Quản lý Đơn Hàng | Admin WaduCase";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    List<OrderWithStatus> ListOrderStatus = ViewBag.ListStatusOrder;
    int Status = ViewBag.Status;
}
<style>
    .ajax_loading p {
        position: absolute;
        left: 0;
        right: 0;
        top: 55%;
    }

    .ajax_loading {
        display: none;
        position: fixed;
        z-index: 9999;
        top: 0;
        left: 0;
        height: 100%;
        width: 100%;
        font-weight: 600;
        text-align: center;
        font-size: 34px;
        padding-top: 337px;
        background: rgba( 255, 255, 255, .7 ) url('../../../../Assets/Admin/images/Pacman-1s-200px.gif') 50% 50% no-repeat;
    }

    body.loading {
        overflow: hidden;
    }

        body.loading .ajax_loading {
            display: block;
        }
</style>

@section jsFooter{


    <script src="/Assets/Admin/ajax/Order.js"></script>

    <script>
        $(document).ready(function () {
            $('#notifymessage').removeClass('hide');
            $('#notifymessage').delay(2000).slideUp(500);

            $(".liststatus").on('change', function (e) {

                //var picker_id = e.target.id;
                var selected_option = $(this).find(":selected"); // get selected option for the changed select only
                var selected_value = selected_option.val();
                var optgroup = selected_option.parent().attr('label');

                window.location = "/admin/order?status=" + parseInt(selected_value);



            });
            $('.vieworder').off('click').on('click', function (e) {
                e.preventDefault();
                var btn = $(this);
                var id = btn.data("id");
                $.ajax({
                    url: '/admin/order/vieworder',
                    type: 'GET',
                    contentType: 'application/json; charset=utf-8',
                    dataType: 'json',
                    ajaxasync: true,
                    data: { id },
                    beforeSend: function () {
                         $("body").addClass("loading");
                    },
                    success: function (response) {

                        console.log(response);
                        $('#myupdatemodal').empty();
                        $('#myupdatemodal').append(response.content);

                    },
                    error: function (err) {
                        alert("Có lỗi xảy ra...");
                    },
                    complete: function () {
                        $("body").removeClass("loading");
                        $('#myupdatemodal').modal('show');
                    }

                });

            });
        });

    </script>
}
<div class="right_col" role="main">
    <div class="">

        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        @if (TempData["AlertMessage"] != null)
                        {
                            <div id="notifymessage" class="alert @TempData["AlertType"]" style="font-size:23px;">
                                @TempData["AlertMessage"]
                            </div>
                        }
                        <h2>Danh sách đơn hàng</h2>
                        <br />

                        <div class="form-group" style="text-align:left">

                            <div class="col-md-9 col-sm-9 col-xs-12">
                                <select class="select2_group form-control liststatus" id="listcategory">
                                    <optgroup label="Trạng thái đơn hàng">

                                        <option @(Status == 1 ? "selected" : "") value="1">
                                            Chưa xử lý@(" (có " + (ListOrderStatus.Where(x => x.StatusID == 1).FirstOrDefault() != null ?
ListOrderStatus.Where(x => x.StatusID == 1).FirstOrDefault().ProductCount : 0) + " đơn hàng)")
                                        </option>
                                        <option @(Status == 2 ? "selected" : "") value="2">
                                            Đang xử lý@(" (có " + (ListOrderStatus.Where(x => x.StatusID == 2).FirstOrDefault() != null ?
ListOrderStatus.Where(x => x.StatusID == 2).FirstOrDefault().ProductCount : 0) + " đơn hàng)")
                                        </option>
                                        <option @(Status == 3 ? "selected" : "") value="3">
                                            Đã hoàn tất@(" (có " + (ListOrderStatus.Where(x => x.StatusID == 3).FirstOrDefault() != null ?
ListOrderStatus.Where(x => x.StatusID == 3).FirstOrDefault().ProductCount : 0) + " đơn hàng)")
                                        </option>
                                        <option @(Status == 4 ? "selected" : "") value="4">
                                            Đã hủy@(" (có " + (ListOrderStatus.Where(x => x.StatusID == 4).FirstOrDefault() != null ?
ListOrderStatus.Where(x => x.StatusID == 4).FirstOrDefault().ProductCount : 0) + " đơn hàng)")
                                        </option>
                                        <option @(Status == 5 ? "selected" : "") value="5">
                                            Đã xóa@(" (có " + (ListOrderStatus.Where(x => x.StatusID == 5).FirstOrDefault() != null ?
ListOrderStatus.Where(x => x.StatusID == 5).FirstOrDefault().ProductCount : 0) + " đơn hàng)")
                                        </option>

                                    </optgroup>

                                </select>
                            </div>
                            @*<a class="btn btn-primary" style="float:right" href="@Url.Action("UpdateProduct", "Product")">Add</a>*@

                        </div>


                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>

                            </li>
                            <li>
                                <a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Sản phẩm</th>
                                    <th>Design</th>
                                    <th>Ngày đặt</th>
                                    <th>Khách hàng</th>
                                    <th>Phone</th>
                                    <th>Địa chỉ</th>
                                    <th>Type</th>
                                    <th>Tổng tiền</th>
                                    <th>Trạng thái</th>
                                    <th>Action</th>
                                </tr>
                            </thead>


                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr id="row_@item.id">
                                        <td>@item.id</td>
                                        <td>@String.Join(" | ", item.listitem.Select(x => x.Name))</td>
                                        <td><img class="img-responsive" src="@Url.Content(item.listitem.First().Thumbnail)" /></td>

                                        @if (@item.createdate == null)
                                        {
                                            <td> @item.createdate </td>
                                        }
                                        else
                                        {
                                            <td> @item.createdate.Value.AddHours(7).ToString("yyyy/MM/dd hh:mm:ss") </td>
                                        }
                                        <td>@item.fullname</td>
                                        <td>@item.phone</td>
                                        <td>@(item.fulladdress + ", " + item.ward + ", " + item.district + ", " + item.province)</td>
                                        <td>@(item.paymenttype == 1 ? "COD" : "Chuyển khoản")</td>
                                        <td>@item.totalmoney.ToString("N0")đ</td>
                                        <td>@item.statusname</td>

                                        <td>
                                            <a class="vieworder btn btn-success btn-view-order" data-id="@item.id"
                                               href="javascript:void(0);">Xem</a>
                                            @if (item.status != 3 && item.status != 4 && item.status != 5)
                                            {
                                                <a href="#" class="btn btn-danger btn-delete-order" data-id="@item.id">Delete</a>

                                            }

                                        </td>

                                    </tr>
                                }

                            </tbody>
                        </table>

                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

<div class="modal fade" id="myupdatemodal" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel" aria-hidden="true">

</div>
<div class="ajax_loading"><p></p></div>

WaduCaseSolution/Areas/Admin/Views/Order/_PartialDetailOrder.cshtml
@using WaduCaseBusiness.Model
@model OrderBO

<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <!-- Modal Header -->
        <div class="modal-header">
            <button type="button" class="close"
                    data-dismiss="modal">
                <span aria-hidden="true">&times;</span>
                <span class="sr-only">Close</span>
            </button>
            <h4 class="modal-title" id="myModalLabel">
                Chi tiết đơn hàng
            </h4>
        </div>

        <!-- Modal Body -->
        <div class="modal-body">
            <div class="form-group">
            </div>
            <div>
                <h2 style="font-style:italic;color:black;">Thông tin khách hàng</h2>
                <div class="item">
                    <div class="col-md-3 col-sm-3">
                        <label>Tên khách hàng:</label>
                    </div>
                    <div class="col-md-9 col-sm-9">
                        <label>@Model.fullname</label>
                    </div>
                </div>
                <div class="item">
                    <div class="col-md-3 col-sm-3">
                        <label>Địa chỉ:</label>
                    </div>
                    <div class="col-md-9 col-sm-9">
                        <label>@(Model.fulladdress + ", " + Model.ward + ", " + Model.district + ", " + Model.province)</label>
                    </div>
                </div>
                <div class="item">
                    <div class="col-md-3 col-sm-3">
                        <label>Note:</label>
                    </div>
                    <div class="col-md-9 col-sm-9">
                        <label>@(String.IsNullOrEmpty(Model.note) ? "<không có>" : Model.note)</label>
                    </div>
                </div>
                <div class="item">
                    <div class="col-md-3 col-sm-3">
                        <label>Phone - Email:</label>
                    </div>
                    <div class="col-md-9 col-sm-9">
                        <label>@(Model.phone + " - " + Model.email)</label>
                    </div>
                </div>
                <div class="item">
                    <div class="col-md-3 col-sm-3">
                        <label>IP đặt hàng:</label>
                    </div>
                    <div class="col-md-9 col-sm-9">
                        <label>@(Model.iporder)</label>
                    </div>
                </div>

            </div>

            <div>
                <h2 style="font-style:italic;color:black;">Thông tin đơn hàng</h2>
                <div class="x_content">
                    <table id="datatable" class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>ProductID</th>
                                <th>Sản phẩm</th>
                                <th>Số lượng</th>
                                <th>Giá</th>
                                <th>DesignImage</th>
                                <th>Danh sách hình</th>
                            </tr>
                        </thead>


                        <tbody>
                            @if (Model.listitem != null)
                            {
                                foreach (var item in Model.listitem)
                                {
                                    <tr id="row_@item.ProductID">
                                        <td>@item.ProductID</td>
                                        <td>@item.Name</td>
                                        <td>@item.Quantity</td>
                                        <td>@item.Price.ToString("N0")đ</td>
                                        <td><img class="img-responsive" src="@Url.Content(item.Thumbnail)" /></td>
                                        <td>
                                            @if (item.ListCustomerImage != null)
                                            {
                                                foreach (var image in item.ListCustomerImage)
                                                {
                                                    <img class="img-responsive" src="@Url.Content(image)" />

                                                }
                                            }


                                        </td>

                                    </tr>
                                }
                            }


                        </tbody>
                    </table>

                </div>

                <div class="item">
                    <div class="col-md-3 col-sm-3">
                        <label>Tổng Giảm trừ:</label>
                    </div>
                    <div class="col-md-9 col-sm-9">
                        <label>@(Model.totaldiscount.ToString("N0"))đ</label>
                    </div>
                </div>
                <div class="item">
                    <div class="col-md-3 col-sm-3">
                        <label>Tiền ship:</label>
                    </div>
                    <div class="col-md-9 col-sm-9">
                        <label>@(Model.shipfee.ToString("N0"))đ</label>
                    </div>
                </div>

                <div class="item">
                    <div class="col-md-3 col-sm-3">
                        <label>Tổng tiền thanh toán:</label>
                    </div>
                    <div class="col-md-9 col-sm-9">
                        <label>@(Model.totalmoney.ToString("N0"))đ</label>
                    </div>
                </div>
                <div class="item">
                    <div class="col-md-3 col-sm-3">
                        <label>Hình thức thanh toán:</label>
                    </div>
                    <div class="col-md-9 col-sm-9">
                        <label>@(Model.paymenttype == 1 ? "Ship Cod" : "Chuyển khoản")</label>
                    </div>
                </div>
                <div class="item">
                    <div class="col-md-3 col-sm-3">
                        <label>Trạng thái đơn hàng:</label>
                    </div>
                    <div class="col-md-9 col-sm-9">
                        <label>@(Model.statusname)</label>
                    </div>
                </div>
                @if (Model.status == 1)
                {
                    <div class="item">
                        <div class="col-md-3 col-sm-3">
                            <label>Ngày đặt hàng:</label>
                        </div>
                        <div class="col-md-9 col-sm-9">
                            <label>@(Model.createdate.Value.AddHours(7).ToString("yyyy/MM/dd hh:mm:ss"))</label>
                        </div>
                    </div>
                }
                else if (Model.status == 3)
                {
                    <div class="item">
                        <div class="col-md-3 col-sm-3">
                            <label>Ngày hoàn tất giao hàng:</label>
                        </div>
                        <div class="col-md-9 col-sm-9">
                            <label>@(Model.deliverydate.Value.AddHours(7).ToString("yyyy/MM/dd hh:mm:ss"))</label>
                        </div>
                    </div>
                }
                else if (Model.status == 4)
                {
                    <div class="item">
                        <div class="col-md-3 col-sm-3">
                            <label>Ngày hủy:</label>
                        </div>
                        <div class="col-md-9 col-sm-9">
                            <label>@(Model.canceleddate.Value.AddHours(7).ToString("yyyy/MM/dd hh:mm:ss"))</label>
                        </div>
                    </div>
                    <div class="item">
                        <div class="col-md-3 col-sm-3">
                            <label>Người hủy:</label>
                        </div>
                        <div class="col-md-9 col-sm-9">
                            <label>@(Model.canceleduser)</label>
                        </div>
                    </div>

                }
                else if (Model.status == 5)
                {
                    <div class="item">
                        <div class="col-md-3 col-sm-3">
                            <label>Ngày xóa:</label>
                        </div>
                        <div class="col-md-9 col-sm-9">
                            <label>@(Model.deleteddate.Value.AddHours(7).ToString("yyyy/MM/dd hh:mm:ss"))</label>
                        </div>
                    </div>
                    <div class="item">
                        <div class="col-md-3 col-sm-3">
                            <label>Người xóa:</label>
                        </div>
                        <div class="col-md-9 col-sm-9">
                            <label>@(Model.deletedduser)</label>
                        </div>
                    </div>

                }

            </div>

            </br>
            @if (Model.status == 1 || Model.status == 2)
            {
                using (Html.BeginForm("UpdateOrderStatus", "Order", FormMethod.Post))
                {
                    <input type="hidden" name="orderid" class="form-control"
                           value="@Model.id" />

                    if (Model.status == 1)
                    {
                        <div class="item form-group">
                            <select name="selectstatus" class="form-control">
                                <option value="2">Đang xử lý</option>
                                <option value="3">Đã hoàn tất</option>
                                <option value="4">Hủy đơn hàng</option>
                            </select>
                        </div>

                    }
                    else
                    {
                        <div class="item form-group">
                            <select name="selectstatus" class="form-control">
                                <option value="1">Chưa xử lý</option>
                                <option value="3">Đã hoàn tất</option>
                                <option value="4">Hủy đơn hàng</option>
                            </select>
                        </div>
                    }
                    <div class="item form-group" id="buttonsubmitarea">
                        <div class="col-md-offset-5 col-md-10">
                            <input type="submit" value="Chuyển trạng thái" class="btn btn-warning" />
                        </div>
                    </div>
                }

            }



        </div>

        <!-- Modal Footer -->
        <div class="modal-footer">
            <button type="button" class="btn btn-default"
                    data-dismiss="modal">
                Close
            </button>

        </div>
    </div>
</div>